use lame_sys::{LameEncoder, Id3Tag, Quality, get_lame_version};
use std::fs::File;
use std::io::Write;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("LAME MP3 Encoder - Simple Example");
    println!("LAME Version: {}", get_lame_version());
    println!("=====================================\n");

    // 1. 创建编码器
    println!("Creating encoder...");
    let mut encoder = LameEncoder::builder()
        .sample_rate(44100)         // 44.1 kHz 标准 CD 音质
        .channels(2)                // 立体声
        .quality(Quality::Standard) // 标准质量
        .bitrate(192)               // 192 kbps
        .build()?;

    println!("✓ Encoder created successfully");

    // 2. 设置 ID3 标签
    println!("Setting ID3 tags...");
    Id3Tag::new(&mut encoder)
        .title("Example Song")?
        .artist("Rust LAME Encoder")?
        .album("Example Album")?
        .year("2024")?
        .comment("Generated by lame-sys example")?
        .track(1)
        .genre("Electronic")?
        .apply()?;

    println!("✓ ID3 tags set");

    // 3. 生成测试音频数据（1 秒的正弦波，440 Hz A音）
    println!("Generating test audio data...");
    let sample_rate = 44100;
    let duration_seconds = 1.0;
    let frequency = 440.0; // A4 音符

    let num_samples = (sample_rate as f32 * duration_seconds) as usize;
    let mut pcm_left = Vec::with_capacity(num_samples);
    let mut pcm_right = Vec::with_capacity(num_samples);

    for i in 0..num_samples {
        let t = i as f32 / sample_rate as f32;
        let sample = (2.0 * std::f32::consts::PI * frequency * t).sin();
        let value = (sample * 16384.0) as i16; // 50% 音量

        pcm_left.push(value);
        pcm_right.push(value);
    }

    println!("✓ Generated {} samples", num_samples);

    // 4. 编码音频数据
    println!("Encoding audio...");
    let mut mp3_data = Vec::new();
    let frame_size = 1152; // LAME 推荐的帧大小

    // MP3 缓冲区大小（LAME 文档推荐）
    let mp3_buffer_size = (1.25 * frame_size as f64) as usize + 7200;
    let mut mp3_buffer = vec![0u8; mp3_buffer_size];

    let mut total_frames = 0;
    let mut total_bytes = 0;

    // 按帧编码
    let mut offset = 0;
    while offset + frame_size <= num_samples {
        let left_frame = &pcm_left[offset..offset + frame_size];
        let right_frame = &pcm_right[offset..offset + frame_size];

        let bytes_written = encoder.encode(left_frame, right_frame, &mut mp3_buffer)?;

        if bytes_written > 0 {
            mp3_data.extend_from_slice(&mp3_buffer[..bytes_written]);
            total_bytes += bytes_written;
            total_frames += 1;
        }

        offset += frame_size;
    }

    // 处理剩余样本
    if offset < num_samples {
        let remaining = num_samples - offset;
        let mut left_frame = pcm_left[offset..].to_vec();
        let mut right_frame = pcm_right[offset..].to_vec();

        // 填充到 frame_size
        left_frame.resize(frame_size, 0);
        right_frame.resize(frame_size, 0);

        let bytes_written = encoder.encode(&left_frame, &right_frame, &mut mp3_buffer)?;

        if bytes_written > 0 {
            mp3_data.extend_from_slice(&mp3_buffer[..bytes_written]);
            total_bytes += bytes_written;
            total_frames += 1;
        }
    }

    // 5. 刷新编码器缓冲区
    let flush_bytes = encoder.flush(&mut mp3_buffer)?;
    if flush_bytes > 0 {
        mp3_data.extend_from_slice(&mp3_buffer[..flush_bytes]);
        total_bytes += flush_bytes;
    }

    println!("✓ Encoded {} frames, {} bytes total", total_frames, total_bytes);

    // 6. 保存 MP3 文件
    let output_filename = "output.mp3";
    println!("Saving to {}...", output_filename);

    let mut file = File::create(output_filename)?;
    file.write_all(&mp3_data)?;

    println!("✓ File saved successfully");

    // 7. 显示统计信息
    println!("\n=====================================");
    println!("Encoding Statistics:");
    println!("  Input samples:  {} (per channel)", num_samples);
    println!("  Sample rate:    {} Hz", sample_rate);
    println!("  Channels:       2 (stereo)");
    println!("  Duration:       {:.2} seconds", duration_seconds);
    println!("  Output size:    {} bytes ({:.2} KB)",
             mp3_data.len(),
             mp3_data.len() as f32 / 1024.0);
    println!("  Bitrate:        192 kbps");
    println!("  Compression:    {:.1}x",
             (num_samples * 2 * 2) as f32 / mp3_data.len() as f32);
    println!("=====================================");

    println!("\n✓ Encoding complete!");
    println!("Play the file with: ffplay {}", output_filename);

    Ok(())
}
